"""update user table

Revision ID: 324170fcdeeb
Revises: 648eb66af7e4
Create Date: 2025-10-08 15:55:33.141371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '324170fcdeeb'
down_revision: Union[str, None] = '648eb66af7e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('phone_number', sa.String(length=20), nullable=True, comment='手机号'))
    op.add_column('user', sa.Column('email', sa.String(length=100), nullable=True, comment='邮箱'))
    op.add_column('user', sa.Column('introduction', sa.Text(), nullable=True, comment='个人介绍'))
    op.create_unique_constraint(None, 'user', ['email'])
    op.create_unique_constraint(None, 'user', ['phone_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'introduction')
    op.drop_column('user', 'email')
    op.drop_column('user', 'phone_number')
    # ### end Alembic commands ###
