"""init tables

Revision ID: 648eb66af7e4
Revises: 
Create Date: 2025-10-06 23:36:15.763121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '648eb66af7e4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('admin_id', mysql.CHAR(length=36), nullable=False, comment='管理员唯一ID'),
    sa.Column('username', sa.String(length=50), nullable=False, comment='登录用户名'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='加密后的密码'),
    sa.Column('role', sa.String(length=50), nullable=False, comment='角色（如：super_admin, editor）'),
    sa.Column('is_active', mysql.TINYINT(display_width=1), nullable=False, comment='账户状态（1:活跃, 0:禁用）'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('admin_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('category',
    sa.Column('category_id', mysql.CHAR(length=36), nullable=False, comment='分类唯一ID'),
    sa.Column('category_name', sa.String(length=100), nullable=False, comment='分类名称（如：食品、美妆）'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='最后更新时间'),
    sa.PrimaryKeyConstraint('category_id'),
    sa.UniqueConstraint('category_name')
    )
    op.create_table('user',
    sa.Column('user_id', mysql.CHAR(length=36), nullable=False, comment='用户唯一ID'),
    sa.Column('openid', sa.String(length=100), nullable=False, comment='微信用户唯一标识'),
    sa.Column('nickname', sa.String(length=100), nullable=True, comment='昵称'),
    sa.Column('avatar_url', sa.String(length=255), nullable=True, comment='头像URL'),
    sa.Column('is_active', mysql.TINYINT(display_width=1), nullable=False, comment='账户状态（1:活跃, 0:禁用）'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='注册时间'),
    sa.Column('last_login_at', sa.DateTime(), nullable=True, comment='最后登录时间'),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('openid')
    )
    op.create_table('product',
    sa.Column('product_id', mysql.CHAR(length=36), nullable=False, comment='产品唯一ID'),
    sa.Column('barcode_or_qr', sa.String(length=100), nullable=False, comment='扫码值（条形码或二维码）'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='产品名称'),
    sa.Column('category_id', mysql.CHAR(length=36), nullable=False, comment='关联的分类ID'),
    sa.Column('production_date', sa.Date(), nullable=True, comment='生产日期'),
    sa.Column('expiration_date', sa.Date(), nullable=True, comment='到期日期'),
    sa.Column('batch_number', sa.String(length=100), nullable=True, comment='批次号'),
    sa.Column('description', sa.Text(), nullable=True, comment='产品详细描述'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='最后更新时间'),
    sa.ForeignKeyConstraint(['category_id'], ['category.category_id'], ),
    sa.PrimaryKeyConstraint('product_id'),
    sa.UniqueConstraint('barcode_or_qr')
    )
    op.create_table('scan_history',
    sa.Column('history_id', mysql.CHAR(length=36), nullable=False, comment='记录唯一ID'),
    sa.Column('user_id', mysql.CHAR(length=36), nullable=False, comment='关联的用户ID'),
    sa.Column('product_id', mysql.CHAR(length=36), nullable=False, comment='关联的产品ID'),
    sa.Column('scan_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='扫码发生时间'),
    sa.ForeignKeyConstraint(['product_id'], ['product.product_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('history_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scan_history')
    op.drop_table('product')
    op.drop_table('user')
    op.drop_table('category')
    op.drop_table('admin')
    # ### end Alembic commands ###
