"""update product

Revision ID: 907eba73e476
Revises: 324170fcdeeb
Create Date: 2025-10-10 22:54:07.654427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '907eba73e476'
down_revision: Union[str, None] = '324170fcdeeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('created_by_admin_id', mysql.CHAR(length=36), nullable=True, comment='添加该产品的管理员ID'))
    op.add_column('product', sa.Column('image_url', sa.String(length=500), nullable=True, comment='产品图像URL'))
    op.create_foreign_key(None, 'product', 'admin', ['created_by_admin_id'], ['admin_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_column('product', 'image_url')
    op.drop_column('product', 'created_by_admin_id')
    # ### end Alembic commands ###
